server:
  port: 8081

# database
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/oasis?characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 30

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: ${REDIS_HOST}

# mybatis
mybatis:
  mapper-locations: mapper/**/*.xml