server:
  port: 8081

# database
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email

  datasource:
    book:
      hikari:
        jdbc-url: jdbc:mysql://${DB_HOST}:3306/book?characterEncoding=utf8
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        auto-commit: false
        maximum-pool-size: 30
    user:
      hikari:
        jdbc-url: jdbc:mysql://${DB_HOST}:3306/user?characterEncoding=utf8
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        auto-commit: false
        maximum-pool-size: 30

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: ${REDIS_HOST}